import { Repository } from 'typeorm';
import { Product } from '../entities/product.entity';
import { Category } from '../entities/category.entity';
import { ProductType } from '../entities/product-type.entity';
import { Unit } from '../entities/unit.entity';
import { PriceHistory } from '../entities/price-history.entity';
import { CreateProductDto } from '../dto/create-product.dto';
import { UpdateProductDto } from '../dto/update-product.dto';
import { CreateCategoryDto } from '../dto/create-category.dto';
import { CreateProductTypeDto } from '../dto/create-product-type.dto';
import { CreateUnitDto } from '../dto/create-unit.dto';
export declare class ProductsService {
    private productsRepository;
    private categoriesRepository;
    private productTypesRepository;
    private unitsRepository;
    private priceHistoryRepository;
    constructor(productsRepository: Repository<Product>, categoriesRepository: Repository<Category>, productTypesRepository: Repository<ProductType>, unitsRepository: Repository<Unit>, priceHistoryRepository: Repository<PriceHistory>);
    create(createProductDto: CreateProductDto, tenantId: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: Category;
        type: ProductType;
        unit: Unit;
        priceHistory: PriceHistory[];
    }>;
    findAll(tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: Category;
        type: ProductType;
        unit: Unit;
        priceHistory: PriceHistory[];
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: Category;
        type: ProductType;
        unit: Unit;
        priceHistory: PriceHistory[];
    }>;
    update(id: string, updateProductDto: UpdateProductDto, tenantId: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: Category;
        type: ProductType;
        unit: Unit;
        priceHistory: PriceHistory[];
    }>;
    remove(id: string, tenantId: string): Promise<{
        message: string;
    }>;
    updateStock(id: string, quantity: number, tenantId: string): Promise<{
        productId: string;
        newQuantity: number;
        isLowStock: boolean;
    }>;
    getLowStockProducts(tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: Category;
        type: ProductType;
        unit: Unit;
        priceHistory: PriceHistory[];
    }[]>;
    createCategory(createCategoryDto: CreateCategoryDto, tenantId: string): Promise<Category>;
    findCategories(tenantId: string): Promise<Category[]>;
    createProductType(createProductTypeDto: CreateProductTypeDto, tenantId: string): Promise<ProductType>;
    findProductTypes(tenantId: string): Promise<ProductType[]>;
    createUnit(createUnitDto: CreateUnitDto, tenantId: string): Promise<Unit>;
    findUnits(tenantId: string): Promise<Unit[]>;
    private sanitizeProduct;
}
