import { Repository } from 'typeorm';
import { Company, CompanyStatus } from '../entities/company.entity';
import { CreateCompanyDto } from '../dto/create-company.dto';
import { UpdateCompanyDto } from '../dto/update-company.dto';
import { Affiliate } from '../../affiliates/entities/affiliate.entity';
import { ReferralTracking } from '../../affiliates/entities/referral-tracking.entity';
export declare class CompaniesService {
    private companiesRepository;
    private affiliatesRepository;
    private referralTrackingRepository;
    constructor(companiesRepository: Repository<Company>, affiliatesRepository: Repository<Affiliate>, referralTrackingRepository: Repository<ReferralTracking>);
    create(createCompanyDto: CreateCompanyDto, ownerId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        activityType: import("../entities/company.entity").ActivityType;
        uniqueCode: string;
        country: string;
        currency: string;
        language: string;
        logoUrl: string;
        address: string;
        status: CompanyStatus;
        trialEndsAt: Date;
        ownerUserId: string;
        affiliateId: string;
        referralTrackingId: string;
        activityCoefficient: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        owner: import("../../users/entities/user.entity").User;
        subscriptions: import("../../subscriptions/entities/subscription.entity").Subscription[];
    }>;
    findOne(id: string, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        activityType: import("../entities/company.entity").ActivityType;
        uniqueCode: string;
        country: string;
        currency: string;
        language: string;
        logoUrl: string;
        address: string;
        status: CompanyStatus;
        trialEndsAt: Date;
        ownerUserId: string;
        affiliateId: string;
        referralTrackingId: string;
        activityCoefficient: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        owner: import("../../users/entities/user.entity").User;
        subscriptions: import("../../subscriptions/entities/subscription.entity").Subscription[];
    }>;
    findByUniqueCode(uniqueCode: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        activityType: import("../entities/company.entity").ActivityType;
        uniqueCode: string;
        country: string;
        currency: string;
        language: string;
        logoUrl: string;
        address: string;
        status: CompanyStatus;
        trialEndsAt: Date;
        ownerUserId: string;
        affiliateId: string;
        referralTrackingId: string;
        activityCoefficient: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        owner: import("../../users/entities/user.entity").User;
        subscriptions: import("../../subscriptions/entities/subscription.entity").Subscription[];
    }>;
    update(id: string, updateCompanyDto: UpdateCompanyDto, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        activityType: import("../entities/company.entity").ActivityType;
        uniqueCode: string;
        country: string;
        currency: string;
        language: string;
        logoUrl: string;
        address: string;
        status: CompanyStatus;
        trialEndsAt: Date;
        ownerUserId: string;
        affiliateId: string;
        referralTrackingId: string;
        activityCoefficient: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        owner: import("../../users/entities/user.entity").User;
        subscriptions: import("../../subscriptions/entities/subscription.entity").Subscription[];
    }>;
    getJoinCode(id: string, tenantId: string): Promise<{
        uniqueCode: string;
    }>;
    private generateUniqueCode;
    private generateRandomCode;
    private generateTrackingToken;
    private getActivityCoefficient;
    private sanitizeCompany;
}
