import { Repository } from 'typeorm';
import { Order, OrderStatus, OrderSource } from '../entities/order.entity';
import { OrderItem } from '../entities/order-item.entity';
import { Product } from '../../products/entities/product.entity';
import { Table } from '../../tables/entities/table.entity';
import { CreateOrderDto } from '../dto/create-order.dto';
import { UpdateOrderDto } from '../dto/update-order.dto';
import { AddItemDto } from '../dto/add-item.dto';
export declare class OrdersService {
    private ordersRepository;
    private orderItemsRepository;
    private productsRepository;
    private tablesRepository;
    constructor(ordersRepository: Repository<Order>, orderItemsRepository: Repository<OrderItem>, productsRepository: Repository<Product>, tablesRepository: Repository<Table>);
    create(createOrderDto: CreateOrderDto, tenantId: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        tableId: string;
        serverUserId: string;
        status: OrderStatus;
        source: OrderSource;
        offlineCreated: boolean;
        clientGeneratedId: string;
        cancelledReason: string;
        cancelledByUserId: string;
        totalAmount: number;
        createdAt: Date;
        updatedAt: Date;
        table?: Table;
        items: OrderItem[];
    }>;
    findAll(tenantId: string): Promise<{
        id: string;
        tenantId: string;
        tableId: string;
        serverUserId: string;
        status: OrderStatus;
        source: OrderSource;
        offlineCreated: boolean;
        clientGeneratedId: string;
        cancelledReason: string;
        cancelledByUserId: string;
        totalAmount: number;
        createdAt: Date;
        updatedAt: Date;
        table?: Table;
        items: OrderItem[];
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        tableId: string;
        serverUserId: string;
        status: OrderStatus;
        source: OrderSource;
        offlineCreated: boolean;
        clientGeneratedId: string;
        cancelledReason: string;
        cancelledByUserId: string;
        totalAmount: number;
        createdAt: Date;
        updatedAt: Date;
        table?: Table;
        items: OrderItem[];
    }>;
    update(id: string, updateOrderDto: UpdateOrderDto, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        tableId: string;
        serverUserId: string;
        status: OrderStatus;
        source: OrderSource;
        offlineCreated: boolean;
        clientGeneratedId: string;
        cancelledReason: string;
        cancelledByUserId: string;
        totalAmount: number;
        createdAt: Date;
        updatedAt: Date;
        table?: Table;
        items: OrderItem[];
    }>;
    addItem(id: string, addItemDto: AddItemDto, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        tableId: string;
        serverUserId: string;
        status: OrderStatus;
        source: OrderSource;
        offlineCreated: boolean;
        clientGeneratedId: string;
        cancelledReason: string;
        cancelledByUserId: string;
        totalAmount: number;
        createdAt: Date;
        updatedAt: Date;
        table?: Table;
        items: OrderItem[];
    }>;
    cancelOrder(id: string, tenantId: string): Promise<{
        message: string;
    }>;
    private sanitizeOrder;
}
