import { ProductsService } from '../services/products.service';
import { CreateProductDto } from '../dto/create-product.dto';
import { UpdateProductDto } from '../dto/update-product.dto';
import { CreateCategoryDto } from '../dto/create-category.dto';
import { CreateProductTypeDto } from '../dto/create-product-type.dto';
import { CreateUnitDto } from '../dto/create-unit.dto';
export declare class ProductsController {
    private readonly productsService;
    constructor(productsService: ProductsService);
    create(createProductDto: CreateProductDto, tenantId: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: import("../entities/category.entity").Category;
        type: import("../entities/product-type.entity").ProductType;
        unit: import("../entities/unit.entity").Unit;
        priceHistory: import("../entities/price-history.entity").PriceHistory[];
    }>;
    findAll(tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: import("../entities/category.entity").Category;
        type: import("../entities/product-type.entity").ProductType;
        unit: import("../entities/unit.entity").Unit;
        priceHistory: import("../entities/price-history.entity").PriceHistory[];
    }[]>;
    getLowStock(tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: import("../entities/category.entity").Category;
        type: import("../entities/product-type.entity").ProductType;
        unit: import("../entities/unit.entity").Unit;
        priceHistory: import("../entities/price-history.entity").PriceHistory[];
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: import("../entities/category.entity").Category;
        type: import("../entities/product-type.entity").ProductType;
        unit: import("../entities/unit.entity").Unit;
        priceHistory: import("../entities/price-history.entity").PriceHistory[];
    }>;
    update(id: string, updateProductDto: UpdateProductDto, tenantId: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        name: string;
        categoryId: string;
        typeId: string;
        unitId: string;
        price: number;
        imageUrl: string;
        currentStock: number;
        alertThreshold: number;
        safetyThreshold: number;
        minStockThreshold: number;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date;
        category: import("../entities/category.entity").Category;
        type: import("../entities/product-type.entity").ProductType;
        unit: import("../entities/unit.entity").Unit;
        priceHistory: import("../entities/price-history.entity").PriceHistory[];
    }>;
    updateStock(id: string, body: {
        quantity: number;
    }, tenantId: string): Promise<{
        productId: string;
        newQuantity: number;
        isLowStock: boolean;
    }>;
    remove(id: string, tenantId: string): Promise<{
        message: string;
    }>;
    createCategory(createCategoryDto: CreateCategoryDto, tenantId: string): Promise<import("../entities/category.entity").Category>;
    findCategories(tenantId: string): Promise<import("../entities/category.entity").Category[]>;
    createProductType(createProductTypeDto: CreateProductTypeDto, tenantId: string): Promise<import("../entities/product-type.entity").ProductType>;
    findProductTypes(tenantId: string): Promise<import("../entities/product-type.entity").ProductType[]>;
    createUnit(createUnitDto: CreateUnitDto, tenantId: string): Promise<import("../entities/unit.entity").Unit>;
    findUnits(tenantId: string): Promise<import("../entities/unit.entity").Unit[]>;
}
